### ISSUE TITLE
[tcp] Acknowledger is sending ACKs without setting the TCP header's sequence number field

### ISSUE THREAD

**Issue by BrianZill** [demikernel/catnip#107]
All TCP Segments are supposed to have a valid sequence number field.  For established connections, the sender should be setting the sequence number field to the current value of SND.NXT.  We're presently sending these ACKs with zero for the sequence number.  If the sequence number on the ACK doesn't fall into the receiver's receive window, the ACK will be ignored (as it could be a long-delayed packet that is no longer valid).  Or at least it should be ignored by the receiving TCP -- we don't currently do that, but that's another bug.

**Comment by ppenna** [comment]
Bug fixed in commit d488757616c4dab075c0bbf18a80bdc53d3c8698.
