### ISSUE TITLE
Test failures hashttlcache

### ISSUE THREAD

**Issue by gatoWololo** [demikernel/catnip#3]
Running `cargo test` leads to several failures. Four of these are in the `hashttlcache` module.

The reason the tests fail is because they all call `try_evict` which doesn't do much:
```rust
pub fn try_evict(&mut self, _count: usize) -> HashMap<K, V> {
        HashMap::default()
    }
```
The rest of the code was commented out and with #2 we deleted the commented code. It isn't immediately why the code was ultimately commented out or what it is supposed to do.

Should we try to get these tests working again? @ppenna thoughts?

**Comment by sujayakar** [comment]
@gatoWololo this code predates me and I never got around to rewriting it. It's pretty jank and doesn't fit into the futures model well. so for the meantime, I effectively made the ARP cache never evict anything, I think.

**Comment by ppenna** [comment]
@gatoWololo I can work on the refactor once I'm at full speed.
