### ISSUE TITLE
[tcp] `test_connect` Regression Test Is Failing

### ISSUE THREAD

**Issue by gatoWololo** [demikernel/catnip#5]
This test currently fails due to a runtime assertion failing. At a high level this test does as follows:
1) Establishes a TCP connection between two parties: Alice (client) and Bob (server).
2) Bob sends some data to Alice.
3) Connection is terminated.

The runtime error happens at this assert:
```rust
pub fn ack_sent(&self, ack_seq: SeqNumber) {
        if self.state.get() == ReceiverState::AckdFin {
            assert_eq!(ack_seq, self.recv_seq_no.get() + Wrapping(1));
        } ...
```
The values of the left-hand and right-hand are off by one.

This is the sequence of events that leads to the issue:
1) Alice sends FIN to close connection to Bob.
2) Bob ACK Alice's FIN.
3) Bob sends FIN to Alice <- **Failure happens here!!!**

Error:
```
thread 'protocols::tcp::tests::test_connect' panicked at 'assertion failed: `(left == right)`
  left: `2760202618`,
 right: `2760202619`',
```

Looking at the log output and stepping through with the debugger I have determined the following:
```
Alice                                            Bob
          FIN, seq=2760202619, ack_seq=0
  [1]     --------------------------------->

          ACK, seq=0, ack_seq=2760202619
  [2]    <----------------------------------

          FIN, seq=142954175, ack_seq=2760202618
  [3]    <----------------------------------   
```

Our runtime assertion `assert_eq!(ack_seq, recv_seq_no + 1);` happens twice. At `[2]` and at `[3]`. It passes the first time but fails the second time. With the following values:
```
[2] assert_eq!(2760202619, 2760202618+ 1); // true
[3] assert_eq!(2760202618, 2760202618+ 1); // false
```

After looking at the details of TCP connection termination I think I found part of the issue. Even though `[1]` passes, I believe the values used for the ACK are wrong. According to the TCP RFC. The ACK reply to a FIN should have the the ack sequence number set to + 1 the value of the seq number of the sender. 

This is indeed happening:
```
        header.ack = true;
        header.ack_num = recv_seq + Wrapping(1);
```

However, even though Alice sent 2760202619. Our ACK reply is using 2760202618 as the recv_seq number!

So Bob is using the wrong starting seq number of 2760202618 and incrementing that to 2760202619, instead of 2760202620. This is due to the fact Bob only updates the received seq number when packets with data arrive. Which makes sense, our seq number represents how many bytes we have received so far.

So Bob doesn't update the seq number after receiving the zero sized payload from the Alice's FIN. Even though Alice bumped her seq number! So Alice now has a seq number of 2760202619 and Bob still thinks it is 2760202618.

I think the bug is Alice increasing her seq number on her FIN message?

I will look into this more... Sorry for the long post! I don't want to introduce new bugs into the system since I don't understand TCP that well.

**Comment by gatoWololo** [comment]
Okay. I have figured out the bug. There were two issues happening as far as I can tell:
1) On a FIN we were increasing the seq number by 1 on the sender. From what I can tell this is incorrect. This figure from the [RFC 793 Transmission Control Protocol, Section 3.5 Closing a Connection:](https://datatracker.ietf.org/doc/html/rfc793#section-3.5) shows how on Step 4 we do not increase our seq number for a FIN.
```
      TCP A                                                TCP B

  1.  ESTABLISHED                                          ESTABLISHED

  2.  (Close)
      FIN-WAIT-1  --> <SEQ=100><ACK=300><CTL=FIN,ACK>  --> CLOSE-WAIT

  3.  FIN-WAIT-2  <-- <SEQ=300><ACK=101><CTL=ACK>      <-- CLOSE-WAIT

  4.                                                       (Close)
      TIME-WAIT   <-- <SEQ=300><ACK=101><CTL=FIN,ACK>  <-- LAST-ACK

  5.  TIME-WAIT   --> <SEQ=101><ACK=301><CTL=ACK>      --> CLOSED

  6.  (2 MSL)
      CLOSED

                         Normal Close Sequence

                               Figure 13.
```
2) The `current_ack` function checks if we have any unacknowledged bytes by comparing our current ack_seq_no (the latest and greatest ack seq no we have sent) vs the `recv_seq_no` (the sequence number we have received). If we have any unacknowledged bytes, we piggy back an ACK to the packet we are about to send and update our ack_seq_no = recv_seq_no. This comparison is being done as:
```rust
pub fn current_ack(&self) -> Option<SeqNumber> {
    ...
    if ack_seq_no != recv_seq_no {
            Some(recv_seq_no)
        } else {
            None
        }
}
```
Which I believe is incorrect for sending a FIN once our receiver state is AckdFin. The error happens as follows (once we have fixed but `1` above):
1) Alice sends a `FIN` with seq_no=2760202618.
2) Bob replies with an` ACK` with ack_number=2760202619.
3) Bob sends a `FIN`, bob's `recv_seq_no`=2760202618 and `ack_seq_no`=2760202619. When these two variables are compared in `current_ack` ` Some(recv_seq_no)` is returned. So we use 2760202618 as the ack seq number. This is wrong. So I changed the comparison to:
```diff
-    if ack_seq_no != recv_seq_no {
+    if ack_seq_no < recv_seq_no {
```

This works as expected.

**Comment by sujayakar** [comment]
awesome debugging and writeup @gatoWololo !
