### ISSUE TITLE
How does catnip cleanly end connections?

### ISSUE THREAD

**Issue by gatoWololo** [demikernel/catnip#7]
@sujayakar I was hoping to get some clarification on how the `closer` module eventually closes a connection. I'm currently getting the following:
```
ERROR [catnip::protocols::tcp::established::background] Connection (fd 1) terminated: Err(ConnectionAborted)

Failed to terminate connection: TrySendError { kind: Disconnected }
thread 'protocols::tcp::tests::test_connect' panicked at 'Failed to terminate connection: TrySendError { kind: Disconnected }', src/protocols/tcp/established/background/mod.rs:58:14
stack backtrace:
```

Looking at:
```rust
pub async fn closer<RT: Runtime>(cb: Rc<ControlBlock<RT>>) -> Result<!, Fail> {
    futures::select_biased! {
        r = rx_ack_sender(cb.clone()).fuse() => r,
        r = tx_fin_sender(cb.clone()).fuse() => r,
        r = close_wait(cb).fuse() => r,
    }
}
```
Both `rx_ack_sender` and `tx_fin_sender` loop forever. So the only way to return is via `close_wait`:
```rust
async fn close_wait<RT: Runtime>(cb: Rc<ControlBlock<RT>>) -> Result<!, Fail> {
    loop {
        // Wait until the FIN we sent has been ACKed.
        let (sender_st, sender_st_changed) = cb.sender.state.watch();
        if sender_st != SenderState::FinAckd {
            sender_st_changed.await;
            continue;
        }

        // Wait until we ACK the FIN that was sent to us.
        let (receiver_st, receiver_st_changed) = cb.receiver.state.watch();
        if receiver_st != ReceiverState::AckdFin {
            receiver_st_changed.await;
            continue;
        }

        // TODO: Wait for 2*MSL if active close.
        return Err(Fail::ConnectionAborted {});
    }
}
```
`close_wait` awaits until the states of our sender and receiver are `FinAcked` and `AckdFin` that makes sense. But then it always errrors? I figured by the time we got passed both of these checks the TCP connection had been "cleanly" ended and we should return a success?

**Comment by sujayakar** [comment]
yep, we can change that to not be an error -- it's the expected protocol condition on close. I think I was trying to reuse that same error code for connection close elsewhere (like when we unexpectedly receive a RST), but I don't think that's too compelling.

the main idea with those closer coroutines is to have the rx ack sender and tx fin sender loop forever, where they're driven by the state changes in the sender and receiver, respectively. they both 1) look for a particular state and then 2) try to push the state machine through the next transition. the closer coroutine, on the other hand, just waits for the TCP state machine to make it to its end and then signal connection close.

lmk if that helps

**Comment by gatoWololo** [comment]
Yes that makes sense and is very helpful.

**Comment by gatoWololo** [comment]
Closing clarifying question.
